### ISSUE TITLE
error while installation: composer issue

### ISSUE THREAD

**Issue by tim-dreier** [proudcommerce/docker-oxid6#20]
Hello, currently the installation on my server is failing due to a missing composer package. I tried to add it myself during installation but i still cannot get it working...

Can you provide a fixed version as soon as possible! I wanted to present my work to a customer today. Many thanks!

```

                    Oxid Migrations CE


Migrating up to 20201029110624 from 0
Migration 20170718124421 failed during Pre-Checks. Error Package "ocramius/proxy-manager" is not installed

Fatal error: Uncaught OutOfBoundsException: Package "ocramius/proxy-manager" is not installed in /var/www/html/vendor/composer/composer/src/Composer/InstalledVersions.php:188
Stack trace:
#0 /var/www/html/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(200): Composer\InstalledVersions::getPrettyVersion('ocramius/proxy-...')
#1 /var/www/html/vendor/ocramius/proxy-manager/src/ProxyManager/Version.php(36): PackageVersions\Versions::getVersion('ocramius/proxy-...')
#2 /var/www/html/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/AbstractBaseFactory.php(62): ProxyManager\Version::getVersion()
#3 /var/www/html/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php(29): ProxyManager\Factory\AbstractBaseFactory->generateProxy('Doctrine\\DBAL\\S...', Array)
#4 /var/www/html/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Provider/LazySchemaDiffProvider.php(61): ProxyManager\Factory\LazyLoadingValueHolderFactory->createProxy('Doctrine\\DBAL\\S...', Object in /var/www/html/vendor/composer/composer/src/Composer/InstalledVersions.php on line 188
run-parts: /entrypoint.d/030-migrations.sh exited with return code 255

```

**Comment by proudcommerce** [comment]
repo updated with oxid 6.3 and php 7.4, please try again ;)
